### ISSUE TITLE
Setting Age and Name length Restrictions for User inputs

### ISSUE THREAD

**Issue by tuanle03** [cnmeow/bdcake#1]
**Problems:**

1. I think we need to limit the age range that users are allowed to input.
- When users enter an age over 100, it's not realistic.
- We should restrict the age range to 1-100.

2. Allowing users to have their names printed on the cake is also an interesting and realistic feature. We can limit the length of the name for convenience in printing it on the cake.

![image](https://github.com/cnmeow/bdcake/assets/66480375/76abf492-2409-4282-8471-bd32f6a66736)

**Comment by cnmeow** [comment]
I fixed it! Thank u
